[package]
name = "extension"
version = "0.1.0"
authors = ["The elenpay Developers"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
signer = { path = "../signer" }
wasm-bindgen = { version="0.2.84" }
yew = { version = "0.20.0", features = ["csr"] }
gloo-events = "0.1.2"
yew-hooks = "0.2.0"

[dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window'
]
