# Use a lightweight Node.js image as the base
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Use a volume for the built extension
VOLUME /app

# Install Mozilla's web-ext tool
RUN npm install -g web-ext@8.7.1

# Default command to serve the extension
CMD ["sh", "-c", "yarn run serve"]
