services:
  build-ext:
    image: nodeguards-companion-build
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/app

  serve-ext:
    image: nodeguards-companion-serve
    build:
      context: .
      dockerfile: Dockerfile.serve
    depends_on:
      build-ext:
        condition: service_completed_successfully
    volumes:
      - ./extension:/app
    ports:
      - "9000:9000"

  upgrade-version:
    image: nodeguards-companion-upgrade
    build:
      context: .
      dockerfile: Dockerfile.utils
    depends_on:
      build-ext:
        condition: service_completed_successfully
    volumes:
      - ./extension:/app
    command: ["node", "scripts/upgradeVersion.js", "patch"]

  web-ext:
    image: nodeguards-companion-web-ext
    build:
      context: .
      dockerfile: Dockerfile.utils
    depends_on:
      build-ext:
        condition: service_completed_successfully
      upgrade-version:
        condition: service_completed_successfully
    volumes:
      - ./extension:/app
    command: >
      sh -c 'web-ext sign \
        --verbose \
        --api-key="$$API_KEY" \
        --api-secret="$$API_SECRET" \
        --channel unlisted \
        --source-dir /app/dist \
        --artifacts-dir /app/signed'

    environment:
      - NODE_ENV=production