version: '3.8'

services:
  build-ext:
    image: nodeguards-companion-build
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/app

  serve-ext:
    image: nodeguards-companion-serve
    build:
      context: .
      dockerfile: Dockerfile.serve
    depends_on:
      build:
        condition: service_completed_successfully
    volumes:
      - ./extension:/app
    ports:
      - "9000:9000"

  upgrade-version:
    image: nodeguards-companion-upgrade
    build:
      context: .
      dockerfile: Dockerfile.serve
    depends_on:
      build:
        condition: service_completed_successfully
    volumes:
      - ./extension:/app
    command: ["node", "scripts/upgradeVersion.js", "patch"]